export const SET_FILTER = 'SET_FILTER';

export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED';

export const TOGGLE_COMPLETE_ALL_REQUEST = 'TOGGLE_COMPLETE_ALL_REQUEST';
export const TOGGLE_COMPLETE_ALL_SUCCESS = 'TOGGLE_COMPLETE_ALL_SUCCESS';
export const TOGGLE_COMPLETE_ALL_FAILED = 'TOGGLE_COMPLETE_ALL_FAILED';

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_FAILED = 'EDIT_TODO_FAILED';

export const TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST';
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';
export const TOGGLE_TODO_FAILED = 'TOGGLE_TODO_FAILED';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';

export const CLEAR_COMPLETED_REQUEST = 'CLEAR_COMPLETED_REQUEST';
export const CLEAR_COMPLETED_SUCCESS = 'CLEAR_COMPLETED_SUCCESS';
export const CLEAR_COMPLETED_FAILED = 'CLEAR_COMPLETED_FAILED';
